mysql:
  master:
    user: 'root'
    password: 'vagrant'
    host: 'localhost'
    dbname: 'silexrest'
  slaves:
    0:
      user: 'root'
      password: 'vagrant'
      host: 'localhost'
      dbname: 'silexrest'

doctrine:
  orm:
    mappings:
      0:
        type: 'annotation'
        namespace: 'MJanssen\Doctrine\Entity'
        alias: 'core'
        path: '%app_path%/src/MJanssen/Doctrine/Entity'
        use_simple_annotation_reader: false

monolog:
  logfile: '/tmp/silexrest/logs/silex_dev.log'

profiler:
  cache_dir: '/tmp/silexrest/cache/profiler'

base.url: ''

hmac_key: 'tempKey'
